name: Create refinement
description: Create a refinement issue to improve a feature
title: "✨ Refinement title"
labels: ["refine", "feature"]
projects: [""]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you want to refine.
      placeholder: Describe the feature you want to refine.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goal
      description: List the goals for this feature.
      value: |
        - Goal 1
        - Goal 2
        - Goal 3

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this feature.
      value: |
        - Criteria 1
        - Criteria 2
        - Criteria 3

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context or screenshots about the feature request here.